require File.expand_path('loja_virtual/lib/livro')
require File.expand_path('loja_virtual/lib/biblioteca')
require File.expand_path('loja_virtual/lib/relatorio')
require File.expand_path('loja_virtual/lib/banco_de_arquivos.rb')
require File.expand_path('loja_virtual/lib/midia')
require File.expand_path('loja_virtual/lib/dvd')